# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of Polyarniy Nikolay
title239: Информатика и рофлы в 239
title2392018: Уроки информатики
title2392019: Уроки информатики
title2392020: Уроки информатики
title2392021: Уроки информатики
title2392022: Уроки информатики
email: PolarNick239@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about computer vision, GPU coding and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url_en: "http://polarnick.com"
url_ru: "http://polarnick.ru"
github_username:  PolarNick239
vk_username:  PolarNick
telegram_username:  PolarNick239

# Build settings
markdown: kramdown
highlighter: rouge
source: .
exclude: [src]

kramdown:
  input: GFM
  hard_wrap: false
